// Generated by CoffeeScript 1.10.0
var Purdy, api_url, colors, got, lang_from, lang_to, log, ok, word;

colors = require("colors");

got = require("got");

Purdy = require("purdy");

log = function() {
  return console.log.apply(console, arguments);
};

ok = function() {
  return Object.keys.apply(Object, arguments);
};

word = process.argv.slice(2)[0];

lang_from = "en";

lang_to = "el";

api_url = "http://mymemory.translated.net/api/get?q=" + word + "&langpair=" + lang_from + "|" + lang_to + "&of=json";

got(api_url, {
  json: true
}).then(function(response) {
  response = response.body;
  log("RESULTS STATUS: " + response.responseStatus);
  log("RESULTS COUNT: " + response.matches.length);
  return log(Purdy.stringify(response));
})["catch"](function(error) {
  return log("Error:", error);
});
