// Generated by CoffeeScript 1.10.0
var api_url, cheerio, got, log, ok, query, sendRequest;

got = require('got');

cheerio = require('cheerio');

query = process.argv.slice(2)[0] || "GOODYS";

log = function() {
  return console.log.apply(console, arguments);
};

ok = function() {
  return Object.keys.apply(Object, arguments);
};

api_url = 'http://11888.ote.gr/web/guest/list-names?_wpType=';

sendRequest = function(query) {
  var theQueryString, url;
  theQueryString = void 0;
  if (query.match(/^\d*$/) === null) {
    theQueryString = 'name&_wpName=' + query + '&_wpWhere=';
  } else {
    theQueryString = 'number&_wpPhone=' + query;
  }
  url = api_url + theQueryString;
  log('SENDING REQUEST: ' + url);
  got(url).then(function(response) {
    var $;
    $ = cheerio.load(response.body);
    return $('ul.results-list-names li').each(function() {
      var address, details, tel, title;
      details = $(this).find('.details');
      title = details.find('span.title').text();
      tel = details.find('div.phone').text();
      address = details.find('div.address').text();
      return log('NAME: ' + title + '\nTELEPHONE: ' + tel + '\nADDRESS: ' + address);
    });
  })["catch"](function(error) {
    return log("Error: " + error);
  });
};

sendRequest(query);
