// Generated by CoffeeScript 1.10.0
var API_URL, crypto, got, password, sender, username;

got = require('got');

crypto = require("crypto");

API_URL = "https://api.smsapi.com/sms.do";

username = "<USERNAME>";

password = "<PASSWORD>";

sender = "<SENDER>";

got.post(API_URL, {
  body: {
    username: username,
    password: crypto.createHash('md5').update(password).digest('hex'),
    to: '<RECIPIENT_MOBILE>',
    from: sender,
    message: "What's up Doc?"
  }
}).then(function(response) {
  return console.log(response.body);
})["catch"](function(e) {
  return console.log("Error: " + e);
});
