// Generated by CoffeeScript 1.10.0
var API_URL, crypto, getBalance, got, password, sendSMS, sender, username;

got = require('got');

crypto = require("crypto");

API_URL = "https://api.smsapi.com/";

username = "<USERNAME>";

password = "<PASSWORD>";

sender = "<SENDER>";

password = crypto.createHash('md5').update(password).digest('hex');

getBalance = function(options) {
  return got.get(API_URL + ("user.do?username=" + username + "&password=" + password + "&credits=1"));
};

sendSMS = function(options) {
  return got.post(API_URL + "sms.do", {
    body: {
      username: username,
      password: password,
      to: options.to,
      from: sender,
      message: options.msg
    }
  });
};

getBalance().then(function(response) {
  return console.log(response.body);
});

sendSMS({
  to: "<RECIPIENT>",
  msg: "<YOUR MESSAGE>"
}).then(function(response) {
  return console.log(response.body);
})["catch"](function(e) {
  return console.log("Error: " + e);
});


/* REFERENCE

Response: ERROR:13 (then NOT catch)
Type: String
Reference: 
  RESPONSE ERROR:13
  ERROR No correct phone numbers

Response: ERROR:103
Type: String
Reference:
  ERROR Cannot send sms, account balance is low
  RESPONSE ERROR:103
 */
