// Generated by CoffeeScript 1.10.0
var Purdy, api_url, cheerio, colors, data, got, lang_from, lang_to, log, ok, word;

colors = require("colors");

got = require("got");

Purdy = require("purdy");

cheerio = require("cheerio");

log = function() {
  return console.log.apply(console, arguments);
};

ok = function() {
  return Object.keys.apply(Object, arguments);
};

word = process.argv.slice(2)[0];

lang_from = "en";

lang_to = "el";

api_url = "http://iate.europa.eu/SearchByQuery.do";

data = {
  "method": "search",
  "saveStats": "true",
  "screenSize": "1280x768",
  "query": word,
  "valid": "Search+",
  "sourceLanguage": lang_from,
  "targetLanguages": lang_to,
  "domain": "0",
  "typeOfSearch": "s"
};

got.post(api_url, {
  body: data
}).then(function(response) {
  var $;
  $ = cheerio.load(response.body);
  return $("#searchResultBody table").filter(function() {
    log($(this).find("tr").eq(1).find("td div.termRecord").text().trim());
    return log($(this).find("tr").eq(2).find("td div.termRecord").text().trim());
  });
})["catch"](function(error) {
  return log("Error:", error);
});
