// Generated by CoffeeScript 1.10.0
var API_KEY, api_url, colors, entry, got, limit, log, ok, op, qs, sourceDictionaries, word;

colors = require("colors");

got = require("got");

log = function() {
  return console.log.apply(console, arguments);
};

ok = function() {
  return Object.keys.apply(Object, arguments);
};

API_KEY = "<YOUR_API_KEY>";

word = process.argv.slice(2)[0] || "resilience";

limit = 10;

sourceDictionaries = 'all';

op = 'definitions';

entry = 'word';

qs = "?api_key=" + API_KEY + "&limit=" + limit + "&sourceDictionaries=" + sourceDictionaries;

api_url = ("https://api.wordnik.com/v4/" + entry + ".json/" + word + "/" + op + "/") + qs;

got(api_url, {
  json: true
}).then(function(response) {
  var output;
  output = response.body;
  return output.forEach(function(word) {
    log(("SOURCE: " + word.sourceDictionary).yellow);
    log(("PART OF SPEECH: " + word.partOfSpeech).magenta);
    log(("DEFINITION: " + word.text).red);
    return log("\n");
  });
})["catch"](function(error) {
  return log("Error: " + error);
});
