// Generated by CoffeeScript 1.10.0
var API_KEY, Purdy, api_url, colors, got, lang_from, lang_to, log, ok, word;

colors = require("colors");

got = require("got");

Purdy = require("purdy");

log = function() {
  return console.log.apply(console, arguments);
};

ok = function() {
  return Object.keys.apply(Object, arguments);
};

API_KEY = "<YOU_API_KEY>";

word = process.argv.slice(2)[0];

lang_from = "en";

lang_to = "gr";

api_url = "http://api.wordreference.com/0.8/" + API_KEY + "/json/" + lang_from + lang_to + "/" + word;

got(api_url, {
  json: true
}).then(function(response) {
  response = response.body;
  return log(Purdy.stringify(response));
})["catch"](function(error) {
  return log("Error:", error);
});
