// Generated by CoffeeScript 1.10.0
var API_KEY, base, colors, getFlickrPhotoUrl, got, keyword, log, ok, parsePhotos, searchFlickr;

got = require("got");

colors = require("colors");

log = function() {
  return console.log.apply(console, arguments);
};

ok = function() {
  return Object.keys.apply(Object, arguments);
};

API_KEY = "<YOUR_API_KEY>";

keyword = process.argv.slice(2)[0] || "miami";

base = "https://api.flickr.com/services/rest/?api_key=" + API_KEY + "&format=rest&format=json&nojsoncallback=1";

getFlickrPhotoUrl = function(image) {
  return "https://farm" + image.farm + ".staticflickr.com/" + image.server + "/" + image.id + "_" + image.secret + ".jpg";
};

searchFlickr = function(keyword) {
  base = base + ("&method=flickr.photos.search&text=" + keyword + "&per_page=10&page=1");
  return got(base).then(function(response) {
    var data;
    data = JSON.parse(response.body);
    return parsePhotos(data.photos.photo);
  })["catch"](function(error) {
    return log("Error: " + error);
  });
};

parsePhotos = function(photoList) {
  return photoList.forEach(function(photo) {
    log(photo.title.magenta + " [ " + photo.owner + " ]");
    return log(("" + (getFlickrPhotoUrl(photo))).yellow);
  });
};

searchFlickr(keyword);
